### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by TaherCCG** [TaherCCG/car-counting-game#10]
Create skeleton for HTML as needed 

- [x] index.html  (menu) #11 
- [x] game1.html (car-colour-counter) #12 
- [x] game2.html (car type counter) #13 
- [ ]game3.html (car brands} #14 

Notes:
1. Create  issue for each html
2. Names of the HTML may change to something more appropriate.

Edit: removed rule-page html as the tutorial will be on each page for the game.

**Comment by TaherCCG** [comment]
Created main index.html structure #7

**Comment by TaherCCG** [comment]
Removed rule-page.html from list as the rules and tutorial will be on the game page for each mode.

**Comment by TaherCCG** [comment]
Completed mode 1 HTML

**Comment by TaherCCG** [comment]
Game Mode 2 basic HTML done
